[versions]
kotlin = "2.0.21"
antlr = "4.13.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
antlr4 = { module = "org.antlr:antlr4", version.ref = "antlr" }
antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
