name: Bump Patch Version on Merge

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump patch version in gradle.properties
        run: |
          current_version=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          IFS='.' read -r major minor patch <<< "$current_version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          sed -i.bak "s/^version=.*/version=$new_version/" gradle.properties
          rm gradle.properties.bak
          echo "Bumped version: $current_version -> $new_version"

      - name: Commit and push version bump
        run: |
          git add gradle.properties
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
